#!/bin/bash -e

# Copyright 2015 tsuru authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/rc/config

export DEBIAN_FRONTEND=noninteractive

apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    make build-essential libssl-dev zlib1g-dev libbz2-dev \
    libreadline-dev libsqlite3-dev curl llvm libncurses5-dev libncursesw5-dev \
    xz-utils tk-dev git libexpat1 libffi-dev tzdata

apt-get install -y --no-install-recommends \
        curl \
        libssl1.0.0 \
        zlib1g \
        libbz2-1.0 \
        libsqlite3-0 \
        libncurses5 \
        libncursesw5 \
        libreadline7 \
        libexpat1 \
        make \
        build-essential

mkdir -p /app/.heroku
ln -s /home/application/python /app/.heroku/python

apt-get autoremove --purge -y

echo "export PATH=/home/application/python/bin:${PATH}" | tee -a ${HOME}/.profile /etc/profile >/dev/null
